import type { Metadata } from "next";
import { Merriweather } from "next/font/google";

import "./globals.css";
import React from "react";

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Jake History",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  header: React.ReactNode;
}

export default function RootLayout({
  children,
  header,
}: Readonly<Props>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css" />
        <title>jake history</title>
      </head>
      <body className={`${merriweather.className}`}>
        {header}
        {children}
      </body>
    </html>
  );
}
